version: '2'
services:
    my-blog:
        build:
            context: .
            dockerfile: Dockerfile
        image: node:16-alpine
        ports:
        - "3000:3000"
        volumes:
        - .:/app
        working_dir: "/app"
        depends_on: 
        - mongodb

    mongodb:
        image: mongo
        container_name: mongodb
        ports:
        - 27017:27017
        environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin

    mongo-express:
        image: mongo-express
        ports:
        - 8080:8081
        environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
        - ME_CONFIG_MONGODB_SERVER=mongodb
